name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    if: github.repository_owner == 'jazzband'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build twine
      - name: Build and check
        run: |
          python -m build --sdist --wheel
          twine check dist/*
      - name: Publish to PyPI
        if: github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/imaplib2/upload
